name: Build PW DHYAN APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools & Platforms
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Generate Wrapper if missing
        run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper --gradle-version 9.3.1
          fi
          chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Ready APK
        uses: actions/upload-artifact@v4
        with:
          name: PW-DHYAN-App-Debug
          path: app/build/outputs/apk/debug/*.apk
